spring:
  application:
    name: order-service
  profiles:
    active: default
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.paymentservice.event,com.example.orderservice.event"
        spring.json.type.mapping: paymentEvent:com.example.orderservice.event.PaymentEvent
    listener:
      ack-mode: MANUAL_IMMEDIATE

user:
  service:
    url: ${USER_SERVICE_URL}

server:
  port: ${SERVER_PORT:8083}

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
    instances:
      userService:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    com.example.orderservice: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.openfeign: DEBUG