apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: microservice-network
type: Opaque
data:
  postgres-db: b3JkZXJkYg==
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXNwYXNz